#!/usr/bin/env bash

usage(){
    echo "Usage: ./purgevarnish [url]"
    echo "  [url] : url à purger"
    echo "      ./purgevarnish / : purge tout le varnish"
    echo "      ./purgevarnish /policy : purge toutes les pages commençant par /policy"
}


if [ "$1" == "" ]; then
    usage;
    exit 1;
fi

docker-compose exec varnish sh -c "varnishadm ban req.url '~' '$1'"