<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary-sd"><button type="submit" class="action login primary-sd" name="send" id="send2"><span><?= $block->escapeHtml(__('Je me connecte')) ?></span><img class="login-sd" alt="login" src="<?php echo $block->getViewFileUrl('Sensdigital_Dyneff::images/sd/login.png'); ?>"></button></div>
                    <div class="secondary-sd"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>


<script type="text/javascript">
    //<![CDATA[
    /*AjaxRequest login to controller @mir*/
    jQuery("#login-form").submit(function(event) {
        var ajaxRequest;
        event.preventDefault();
        jQuery("#ajaxResponse").html('');
        var values = jQuery(this).serialize();
        var url=jQuery(this).attr("action");

            ajaxRequest = jQuery.ajax({
                url: "<?php echo $block->getUrl('ajaxlogin/account/loginPost'); ?>",
                //url: url,
                type: "POST",
                beforeSend: function () {
                    jQuery('#loader-sd').show();
                },
                data: values
            });

            ajaxRequest.done(function (response, textStatus, jqXHR) {
                // show successfully for submit message
                jQuery("#ajaxResponse").html(response);
                jQuery('#loader-sd').hide();
                if(response == '200'){
                    jQuery("#ajaxResponse").html('Connexion réussie ! vous allez être redirigé(e) vers l\'étape suivante.');
                    jQuery('#loader-sd').show();
                    jQuery('#addToCart-fioul').removeAttr('disabled');
                    jQuery('#addToCart-fioul').trigger('click');
                    jQuery('#addToCart-fioul').attr('disabled', 'disabled');
                }
            });

            /* On failure of request this function will be called  */
            ajaxRequest.fail(function () {
                // show error
                jQuery("#ajaxResponse").html('Oups, Une erreur s\'est produite, veuillez réessayer plus tard !');
                jQuery('#loader-sd').hide();
            });
    });
    //]]>
</script>
